#
# JBoss, Home of Professional Open Source.
# See the COPYRIGHT.txt file distributed with this work for information
# regarding copyright ownership.  Some portions may be licensed
# to Red Hat, Inc. under one or more contributor license agreements.
# 
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301 USA.
#

BasicInterceptor.ProcessTree_for__4=ProcessTree for


ConnectorManager.not_in_valid_state=Connector is not in OPEN state

ConnectorManagerImpl.Initializing_connector=Initializing connector {0}
Cancel_request_failed=AtomicRequest {0} failed to cancel.

ConnectorWorker.MaxResultRowsExceed=The number of result rows has exceeded the maximum result rows "{0}"
ConnectorWorker.zero_size_non_last_batch=Connector returned a 0 row non-last batch: {0}.
ConnectorWorker.process_failed=Connector worker process failed for atomic-request={0}
ConnectorWorker.ConnectorWorker_result_set_unexpected_columns=Could not process stored procedure results for {0}.  Expected {1} result set columns, but was {2}.  Please update your models to allow for stored procedure results batching.


DataTierManager.could_not_obtain_connector_binding=Could not obtain connection factory for model {0} in VDB name= {1}, version {2}


DQPCore.Unable_to_load_metadata_for_VDB_name__{0},_version__{1}=Unable to load metadata for VDB name= {0}, version= {1}
DQPCore.Unknown_query_metadata_exception_while_registering_query__{0}.=Unknown query metadata exception while registering query: {0}.
DQPCore.Clearing_prepared_plan_cache=Clearing prepared plan cache
DQPCore.The_request_has_been_closed.=The request {0} has been closed.
DQPCore.The_atomic_request_has_been_cancelled=The atomic request {0} has been canceled.
DQPCore.failed_to_cancel=Failed to Cancel request, as request already finished processing




ProcessWorker.failed_rollback=Failed to properly rollback autowrap transaction properly
ProcessWorker.error=Unexpected exception for request {0}
ProcessWorker.processing_error=Processing exception ''{0}'' for request {1}.  Exception type {2} thrown from {3}. Enable more detailed logging to see the entire stacktrace.


# ==========================================
# Error Messages for the dqp Package
# ==========================================
#

# application (000)

# interceptor (001)

# internal (002)

# from server package of last release
# #datatier (018.003)

# #query (018.005)
ERR.018.005.0095 = User <{0}> is not entitled to action <{1}> for 1 or more of the groups/elements/procedures.

# services (003)

Request.Invalid_character_in_query=Bind variables (represented as "?") were found but are allowed only in prepared or callable statements.

ProcessWorker.wrongdata=Wrong type of data found or no data found; expecting streamable object from the buffer manager.
ProcessWorker.LobError=An error occurred during streaming of Lob Chunks to Client.

TransactionServer.existing_transaction=Client thread already involved in a transaction. Transaction nesting is not supported. The current transaction must be completed first.
TransactionServer.no_transaction=No transaction found for client {0}.
TransactionServer.concurrent_transaction=Concurrent enlistment in global transaction {0} is not supported.
TransactionServer.no_global_transaction=Expected an existing global transaction {0} but there was none for client {1}
TransactionServer.unknown_flags=Unknown flags
TransactionServer.no_global_transaction=No global transaction found for {0}.
TransactionServer.wrong_transaction=Client is not currently enlisted in transaction {0}.
TransactionServer.resume_failed=Cannot resume, transaction {0} was not suspended by client {1}.
TransactionServer.existing_global_transaction=Global transaction {0} already exists.
TransactionServer.suspended_exist=Suspended work still exists on transaction {0}.

 

TransformationMetadata.does_not_exist._1=does not exist.
TransformationMetadata.Error_trying_to_read_virtual_document_{0},_with_body__n{1}_1=Error trying to read virtual document {0}, with body \n{1}
TransformationMetadata.Unknown_support_constant___12=Unknown support constant: 
TransformationMetadata.QueryPlan_could_not_be_found_for_physical_group__6=QueryPlan could not be found for physical group 
TransformationMetadata.InsertPlan_could_not_be_found_for_physical_group__8=InsertPlan could not be found for physical group 
TransformationMetadata.InsertPlan_could_not_be_found_for_physical_group__10=InsertPlan could not be found for physical group 
TransformationMetadata.DeletePlan_could_not_be_found_for_physical_group__12=DeletePlan could not be found for physical group 
TransformationMetadata.Error_trying_to_read_schemas_for_the_document/table____1=Error trying to read schemas for the document/table : 
TransformationMetadata.Invalid_type=Invalid type: {0}.
TransformationMetadata.does_not_exist._1=does not exist.
TransformationMetadata.0={0} ambiguous, more than one entity matching the same name
TransformationMetadata.Error_trying_to_read_virtual_document_{0},_with_body__n{1}_1=Error trying to read virtual document {0}, with body \n{1}
TransformationMetadata.Unknown_support_constant___12=Unknown support constant: 
TransformationMetadata.QueryPlan_could_not_be_found_for_physical_group__6=QueryPlan could not be found for physical group 
TransformationMetadata.InsertPlan_could_not_be_found_for_physical_group__8=InsertPlan could not be found for physical group 
TransformationMetadata.InsertPlan_could_not_be_found_for_physical_group__10=InsertPlan could not be found for physical group 
TransformationMetadata.DeletePlan_could_not_be_found_for_physical_group__12=DeletePlan could not be found for physical group 
TransformationMetadata.Error_trying_to_read_schemas_for_the_document/table____1=Error trying to read schemas for the document/table : 
TransformationMetadata.Invalid_type=Invalid type: {0}.

CachedFinder.no_connector_found=No connector with jndi-name {0} found for Model {1} with source name {2} 
translator_not_found=Translator {0} not accessible.
datasource_not_found=Data Source {0} not accessible.

RequestWorkItem.cache_nondeterministic=Caching command '{0}'' at a session level, but less deterministic functions were evaluated. 
not_found_cache=Results not found in cache
failed_to_unwrap_connection=Failed to unwrap the source connection.
